name: todos
services:
  todos-app:
    # If container name to be todos-app, we need to assign the container_name as below since,
    # it considers the first word(todos) as service name and excludes from the container name.
    container_name: todos-todos-app
    build:
      context: ./app
    environment:
      NODE_ENV: production
    ports:
      - 3046:3000
      - 35729:35729
    depends_on:
      - todos-db
      - todos-cache
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync
  todos-db:
    image: td-db
    container_name: todos-todos-db
    build:
      context: ./db
    ports:
      - 27017:27017
  todos-cache:
    image: td-cache
    container_name: todos-todos-cache
    build:
      context: ./cache
    ports:
      - 6379:6379
